POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1bGxlIiwiaWQiOiI2MDE0M2NjOGU3ZmI5MDFlOGYwYWJmNWUiLCJpYXQiOjE2MTE5MzkxMjd9.rSfJq_RdZNxO7SfqGHqgcvthA4TBoLEp0JPqKDRHLTg

{
    "title": "Juliusblog",
    "author": "Dunno",
    "url": "www.someurl23.com",
    "likes": 1
}